import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { type ReactElement } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement => {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
